version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapipet
